//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::blog::Entity as Blog;
pub use super::comment::Entity as Comment;
pub use super::goods::Entity as Goods;
pub use super::user::Entity as User;
