package cn.magicalsheep.client.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class Mode2Frame {
    public JPanel root;
    public JProgressBar progressBar;
    public JLabel score;
    public JButton aButton;
    public JButton cButton;
    public JButton bButton;
    public JButton dButton;
    public JLabel word;
    public JLabel msg;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):grow(0.1),left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):grow,left:5dlu:noGrow,fill:max(d;4px):grow(0.1)", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        root.add(panel1, cc.xy(1, 9, CellConstraints.DEFAULT, CellConstraints.FILL));
        aButton = new JButton();
        Font aButtonFont = this.$$$getFont$$$(null, -1, 18, aButton.getFont());
        if (aButtonFont != null) aButton.setFont(aButtonFont);
        aButton.setText("A. ");
        panel1.add(aButton, cc.xy(3, 3));
        cButton = new JButton();
        Font cButtonFont = this.$$$getFont$$$(null, -1, 18, cButton.getFont());
        if (cButtonFont != null) cButton.setFont(cButtonFont);
        cButton.setText("C. ");
        panel1.add(cButton, cc.xy(3, 5));
        bButton = new JButton();
        Font bButtonFont = this.$$$getFont$$$(null, -1, 18, bButton.getFont());
        if (bButtonFont != null) bButton.setFont(bButtonFont);
        bButton.setText("B. ");
        panel1.add(bButton, cc.xy(5, 3));
        dButton = new JButton();
        Font dButtonFont = this.$$$getFont$$$(null, -1, 18, dButton.getFont());
        if (dButtonFont != null) dButton.setFont(dButtonFont);
        dButton.setText("D. ");
        panel1.add(dButton, cc.xy(5, 5));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:grow", "center:d:grow,top:5dlu:noGrow,center:max(d;4px):grow(0.1)"));
        root.add(panel2, cc.xy(1, 7, CellConstraints.DEFAULT, CellConstraints.FILL));
        word = new JLabel();
        Font wordFont = this.$$$getFont$$$(null, Font.BOLD, 48, word.getFont());
        if (wordFont != null) word.setFont(wordFont);
        word.setHorizontalAlignment(0);
        word.setText("Word");
        panel2.add(word, cc.xy(1, 1));
        msg = new JLabel();
        Font msgFont = this.$$$getFont$$$(null, -1, 14, msg.getFont());
        if (msgFont != null) msg.setFont(msgFont);
        msg.setHorizontalAlignment(10);
        msg.setText("Msg");
        panel2.add(msg, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.CENTER));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:max(d;4px):grow(0.1),left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):grow(0.1)", "center:d:noGrow"));
        root.add(panel3, cc.xy(1, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        progressBar = new JProgressBar();
        progressBar.setMaximumSize(new Dimension(32767, 4));
        progressBar.setMinimumSize(new Dimension(10, 4));
        progressBar.setPreferredSize(new Dimension(146, 8));
        progressBar.setString("0%");
        progressBar.setValue(0);
        panel3.add(progressBar, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.CENTER));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow"));
        root.add(panel4, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        score = new JLabel();
        Font scoreFont = this.$$$getFont$$$(null, -1, 20, score.getFont());
        if (scoreFont != null) score.setFont(scoreFont);
        score.setHorizontalAlignment(0);
        score.setText("分数：10");
        panel4.add(score, cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
